# This is a basic workflow to help you get started with Actions

name: Automatic Release on Tag

# Controls when the workflow will run
on:
  # Triggers the workflow on tag creation to push out a release
  push:
    tags:
    - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: main

      - name: Make build script executable
        run: chmod +x .github/scripts/build_release.sh
          
      # Zip the deployment for distribution
      - name: Run build script
        run: .github/scripts/build_release.sh ${{ github.ref_name }} ${{ github.repository }}
      
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release create --draft "${{ github.ref_name }}" --title "${{ github.ref_name }}" --generate-notes

      - name: Upload Template Files to Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload "${{ github.ref_name }}" "build/deploy.json" "build/createUiDefinition.json" "build/Templates/ArcSQLSinglePaneofGlass.json" "build/Templates/SQLLicensingSummary.json"

      - name: Publish Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release edit "${{ github.ref_name }}" --draft=false

      - uses: LanceMcCarthy/Action-AzureBlobUpload@v3
        name: Uploading to Azure storage...
        with:
          connection_string: ${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
          container_name: release
          source_folder: build/upload/
          delete_if_exists: true

      - uses: azure/login@v2
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Template
        uses: azure/bicep-deploy@v2
        with:
            type: deployment
            operation: validate
            name: Development
            scope: resourceGroup
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}
            template-file: build/deploy.json

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          message: Update Deployment Url to current release
          add: README.md

      - name: Update Git Tag
        uses: jimeh/update-tags-action@v1
        with:
          tags: ${{ github.ref_name }}